Initial release
polarityio/cortex-xsoar-ioc-submission pull request #1
Opened 2021-01-18 23:54 UTC by penwoodjon

2021-01-26 14:48 UTC, sarus requested changes
@penwoodjon Looking really great.  Some small changes requested here and there primarily on verbiage.

Thank you!

2021-01-26 14:48 UTC, sarus commented on config/config.js
> +        'The base URL for the Cortex XSOAR API which should include the schema (i.e., https://)',
My mistake but `schema` should actually be `scheme`.  I think this typo started working its way into a lot of integrations.  I would actually switch to `protocol` as that seems to be more widely used:

```
The base URL for the Cortex XSOAR API which should include the protocol (i.e., https://)
```

2021-01-26 14:48 UTC, sarus commented on templates/block.hbs
> +          <input
I'd consider making this a text area (maybe limit it to 3 lines) since this is a details field where there will likely be more information typed in than a single line.

2021-01-26 14:48 UTC, sarus commented on templates/block.hbs
> +          {{#if createIndicatorsIsRunning}}
I'm not seeing the spinner activate here when submitting an IOC.  It also looks like there should be a success message that says "Successfully Created IOCs"? but I don't see that either.

2021-01-27 17:45 UTC, penwoodjon commented on integration.js
@sarus Totally agree on the URL option type! Would also be nice to have some default Option Validation flags as well built into the framework, like one for the a string existing for example as option validation seems to pretty consistently use that one. Thanks for the heads up on the new copy of the options object.  I'll modify it to use your code as I agree it is more readable.

2021-01-27 18:22 UTC, penwoodjon commented on templates/block.hbs
> +          {{#if createIndicatorsIsRunning}}
@radar989 and I cant seem to replicate 🤔 
<img width="512" alt="Screen Shot 2021-01-27 at 12 07 17 PM" src="https://user-images.githubusercontent.com/58269952/106035873-3a0b9600-609a-11eb-8ce7-23eac59b54ca.png">

2021-01-27 18:37 UTC, penwoodjon commented on templates/block.hbs
> +          {{#if createIndicatorsIsRunning}}
@radar989 and I weren't able to replicate the message not showing up on either, but I was able to on the loading icon. 
 Just pushed a fix!  
<img width="512" alt="Screen Shot 2021-01-27 at 12 07 17 PM" src="https://user-images.githubusercontent.com/58269952/106037374-36790e80-609c-11eb-84c8-4fa57a5f0b2c.png">

2021-01-29 15:05 UTC, sarus commented
@penwoodjon Seeing some odd behavior with adding a new indicator:

Added `3.3.3.3` and it showed as added:

![image](https://user-images.githubusercontent.com/306319/106291224-61d53800-6219-11eb-8272-a2ac3e59e549.png)

Then clicked on the "Search" button (magnifying glass) to cause the search to rerun and it shows up as not in Cortex:

![image](https://user-images.githubusercontent.com/306319/106291308-76b1cb80-6219-11eb-922a-8a1b21108ced.png)

2021-01-29 15:27 UTC, sarus commented
Might need to add a min width to the submit button to prevent the text from stacking and getting a bit cutoff.  This is for both submit buttons:

![image](https://user-images.githubusercontent.com/306319/106293946-93033780-621c-11eb-94ae-28a7e8f311aa.png)

2021-01-29 16:50 UTC, merged